"""Read-only platform account dashboard; all data routes enforce admin access."""

ADMIN_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Ninai · Admin</title>
<style>
:root{font:15px system-ui,sans-serif;color:#0b302b;background:#f4efe5}*{box-sizing:border-box}body{margin:0}a{color:inherit}header{background:#0b302b;color:#f4efe5;padding:22px max(24px,calc((100% - 1200px)/2));display:flex;align-items:center;justify-content:space-between;gap:24px}header strong{font-size:24px;letter-spacing:-1px}nav{display:flex;gap:20px;align-items:center}main{max-width:1248px;margin:auto;padding:38px 24px}h1{font-size:clamp(32px,5vw,54px);letter-spacing:-2px;margin:10px 0}h2{margin-top:0}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:11px;font-weight:800}.muted{color:#53685f;line-height:1.6}.intro{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.metric,.panel{border:1px solid #cbd0bd;background:#fbf8f1;border-radius:18px 18px 5px 18px;padding:22px}.metric b{display:block;font-size:38px;letter-spacing:-1px;margin:12px 0}.metric:first-child{background:#dcef7b}.panel{margin-top:24px}.toolbar,.pager{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.toolbar form{display:flex;gap:10px;align-items:end;flex-wrap:wrap}label{font-size:13px;font-weight:650;display:block}input{display:block;width:280px;max-width:100%;margin-top:6px;border:1px solid #82988b;padding:12px;border-radius:8px;font:inherit;background:white}button,.button{min-height:44px;padding:10px 18px;border:1px solid #0b302b;border-radius:24px;background:#0b302b;color:#fbf8f1;font:inherit;cursor:pointer;text-decoration:none}button.secondary{background:transparent;color:#0b302b}button:disabled{opacity:.45;cursor:default}:focus-visible{outline:3px solid #ff6846;outline-offset:4px}.table-wrap{overflow:auto;margin:22px 0}table{width:100%;border-collapse:collapse;font-size:14px}th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#53685f}td,th{padding:15px 12px;border-bottom:1px solid #dce0d2;vertical-align:top}td small{display:block;color:#53685f;margin-top:5px}td:first-child{padding-left:0}code{font-size:12px;overflow-wrap:anywhere}.badge{display:inline-block;padding:4px 9px;border-radius:20px;background:#e6ebda;font-size:12px}.error{color:#8c2917;background:#fff1e8;padding:16px;border-radius:8px}.details-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.details-grid p{overflow-wrap:anywhere}[hidden]{display:none!important}.skip{position:absolute;left:10px;top:-100px}.skip:focus{top:10px;background:white;padding:15px;color:#0b302b}@media(max-width:800px){.metrics,.details-grid{grid-template-columns:1fr 1fr}header,.intro{align-items:flex-start;flex-direction:column}nav{flex-wrap:wrap}}@media(max-width:480px){.metrics,.details-grid{grid-template-columns:1fr}main{padding:24px 16px}input{width:100%}}
</style></head><body><a class="skip" href="#main">Skip to dashboard</a><header><strong>ninai <span class="eyebrow">/ Admin</span></strong><nav aria-label="Account"><a href="/control">Mac setup</a><a href="https://ninai.io">Website ↗</a><a href="/control/logout">Sign out</a></nav></header>
<main id="main"><div class="intro"><div><p class="eyebrow">Platform overview</p><h1>See who’s getting started.</h1><p class="muted">Accounts, sign-ins, and official installer downloads.</p></div><button id="refresh" class="secondary">Refresh</button></div>
<p id="notice" role="status" aria-live="polite">Loading account activity…</p><section id="metrics" class="metrics" aria-label="Account metrics"></section>
<section class="panel" aria-labelledby="users-heading"><div class="toolbar"><div><h2 id="users-heading">Users</h2><span id="count" class="muted"></span></div><form id="search-form"><label>Find an account<input id="search" type="search" maxlength="200" placeholder="Name, email, or user ID"></label><button>Search</button></form></div><div class="table-wrap"><table><thead><tr><th>Account</th><th>Signed up</th><th>Last sign-in</th><th>Logins</th><th>Downloads</th><th>Connections</th><th>Details</th></tr></thead><tbody id="users"></tbody></table></div><div class="pager"><button id="previous" class="secondary" disabled>← Previous</button><span id="page" class="muted"></span><button id="next" class="secondary" disabled>Next →</button></div></section>
<section id="detail" class="panel" hidden aria-labelledby="detail-heading" tabindex="-1"></section>
<p class="muted">Successful login counts begin when this dashboard is deployed. A download confirms the installer was requested; it does not confirm installation. Connection counts cover the hosted preview only. Local Mac vaults and local agent activity are not collected.</p></main>
<script>
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString():'Not recorded';let offset=0,total=0,busy=false,detailRequest=0;const limit=25;
async function api(path){const r=await fetch('/api/control/admin'+path,{credentials:'same-origin',cache:'no-store'});if(!r.ok){throw Error(r.status===401?'Your session expired. Sign in again from Mac setup.':r.status===403?'This account does not have platform admin access.':'Account data could not be loaded. Please retry.')}return r.json()}
function status(message,error=false){$('#notice').textContent=message;$('#notice').className=error?'error':'muted'}
async function load(){if(busy)return;busy=true;$('#refresh').disabled=true;$('#search-form button').disabled=true;$('#previous').disabled=true;$('#next').disabled=true;status('Refreshing…');try{const [m,u]=await Promise.all([api('/overview'),api('/users?'+new URLSearchParams({q:$('#search').value,limit,offset}))]);total=u.total;$('#metrics').innerHTML=[['Active accounts',m.users,'Registered in Ninai'],['New this week',m.signups_7d,'Joined in the last 7 days'],['Signed in this week',m.signed_in_7d,'Unique accounts · last 7 days'],['Downloaded Ninai',m.downloaders,'Unique active accounts']].map(([label,note,sub])=>`<article class="metric"><span>${esc(label)}</span><b>${esc(note)}</b><small>${esc(sub)}</small></article>`).join('');$('#count').textContent=total+' matching accounts';$('#users').innerHTML=u.items.length?u.items.map(u=>`<tr><td><b>${esc(u.display_name)}</b><small>${esc(u.email)}</small>${u.deleted_at?'<span class="badge">Deleted</span>':''}</td><td>${esc(date(u.created_at))}</td><td>${esc(date(u.last_login_at))}</td><td>${esc(u.login_count)}</td><td>${esc(u.downloads)}</td><td>${esc(u.connections)}</td><td><button class="secondary" data-user="${esc(u.id)}" aria-label="View ${esc(u.display_name)}">View</button></td></tr>`).join(''):'<tr><td colspan="7">No matching accounts.</td></tr>';$('#page').textContent=total?`${offset+1}–${Math.min(offset+limit,total)} of ${total}`:'0 accounts';status('Updated '+new Date().toLocaleTimeString()+` · ${m.downloads} downloads · ${m.workspaces} active workspaces · ${m.connections} hosted connections`)}catch(e){$('#metrics').innerHTML='';$('#users').innerHTML='';$('#count').textContent='';$('#page').textContent='';total=0;status(e.message,true)}finally{busy=false;$('#refresh').disabled=false;$('#search-form button').disabled=false;$('#previous').disabled=offset===0;$('#next').disabled=offset+limit>=total}}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'">No records.</td></tr>')+'</tbody></table></div>'}
async function details(id){const request=++detailRequest;$('#detail').hidden=false;$('#detail').textContent='Loading account…';try{const d=await api('/users/'+encodeURIComponent(id));if(request!==detailRequest)return;const u=d.user;$('#detail').innerHTML=`<div class="toolbar"><h2 id="detail-heading">${esc(u.display_name)}</h2><button id="close-detail" class="secondary">Close details</button></div><div class="details-grid"><div><p>${esc(u.email)}</p><p class="muted">User ID <code>${esc(u.id)}</code></p><p>Status: ${u.deleted_at?'Deleted':'Active'}</p></div><div><p>Joined: ${esc(date(u.created_at))}</p><p>Last sign-in: ${esc(date(u.last_login_at))}</p><p>Successful logins: ${esc(u.login_count)}</p></div></div><h3>Workspaces</h3>${table(['Name','Plan','Role','Status'],d.workspaces.map(w=>[w.name,w.plan,w.role,w.deleted_at?'Deleted':w.revoked_at?'Membership revoked':'Active']))}<h3>Hosted connections</h3>${table(['Name','Provider','Client','Status','Last used'],d.connections.map(c=>[c.display_name,c.provider,c.client_type,c.status,date(c.last_seen_at)]))}<h3>Installer downloads</h3>${table(['Platform','Requested','Artifact SHA-256'],d.downloads.map(x=>[x.platform,date(x.created_at),x.artifact_sha256]))}<p class="muted">Each section shows up to the 100 most recent records.</p>`;$('#close-detail').onclick=()=>{$('#detail').hidden=true;detailRequest++};$('#detail').focus()}catch(e){if(request===detailRequest)$('#detail').textContent=e.message}}
$('#users').onclick=e=>{const button=e.target.closest('[data-user]');if(button)details(button.dataset.user)};$('#refresh').onclick=load;$('#search-form').onsubmit=e=>{e.preventDefault();if(!busy){offset=0;load()}};$('#previous').onclick=()=>{if(!busy){offset=Math.max(0,offset-limit);load()}};$('#next').onclick=()=>{if(!busy){offset+=limit;load()}};load();
</script></body></html>'''
