"""Dependency-free control-center page served by the hosted API."""

import json

CONTROL_CENTER_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b302b"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="apple-touch-icon" href="/favicon.svg">
<title>Ninai Control Center — Hosted AI memory</title><style>
:root{font:15px "Avenir Next",Avenir,system-ui,sans-serif;color:#111512;background:#f4efe5;--vault:#0b302b;--paper:#f4efe5;--soft:#fbf8f1;--signal:#ff6846;--permit:#dcef7b;--moss:#9cb5a8;--line:rgba(17,21,18,.18)}*{box-sizing:border-box}html{background:var(--paper)}body{margin:0;background:var(--paper)}
.topbar{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);padding:0 max(24px,calc((100vw - 1180px)/2));background:rgba(244,239,229,.94)}.wordmark{width:112px;display:inline-flex;align-items:center;text-decoration:none}.wordmark img{width:112px;height:auto;display:block}.topbar__meta{display:flex;align-items:center;gap:12px;color:#52615b;font:11px ui-monospace,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase}.return-mark{width:24px;height:24px;display:block;border-radius:7px}
main,.dashboard-shell{width:min(calc(100% - 48px),1180px);margin:0 auto}.onboarding{padding:clamp(70px,9vw,130px) 0 80px}.onboarding__hero{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:clamp(50px,9vw,130px);align-items:end}.eyebrow{margin:0 0 22px;color:#52615b;font:11px ui-monospace,Menlo,monospace;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.onboarding h1{max-width:780px;margin:0;font-size:clamp(4rem,7.2vw,7.2rem);font-weight:850;letter-spacing:-.075em;line-height:.86}.onboarding__intro{padding-bottom:8px}.onboarding__intro p{margin:0 0 28px;color:#52615b;font-size:1.15rem;line-height:1.55}.cta-row{display:flex;flex-wrap:wrap;gap:12px}.button-link,button{min-height:48px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #111512;border-radius:999px;padding:0 22px;cursor:pointer;color:#111512;background:var(--paper);font:inherit;font-weight:800;text-decoration:none}.button-link--primary{background:var(--signal);box-shadow:7px 7px 0 var(--vault)}.button-link--secondary{color:var(--paper);background:var(--vault)}button:hover,.button-link:hover{transform:translateY(-2px)}
.onboarding__proof{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;border-top:1px solid var(--line);margin-top:90px;padding-top:28px}.proof{min-height:150px;border:1px solid var(--line);border-radius:24px 24px 7px 24px;padding:24px;background:var(--soft)}.proof span{display:inline-grid;width:30px;height:30px;place-items:center;border:1px solid var(--vault);border-radius:50%;margin-bottom:30px;color:var(--vault);background:var(--permit);font:11px ui-monospace,Menlo,monospace}.proof h2{margin:0 0 8px;font-size:1.15rem}.proof p{margin:0;color:#59665f;line-height:1.5}.onboarding__note{display:flex;justify-content:space-between;gap:30px;border-top:1px solid var(--line);margin-top:28px;padding-top:18px;color:#59665f;font-size:.82rem}.onboarding__note a{color:inherit}
.dashboard-shell{padding:34px 0 80px}.sessionbar{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);margin-bottom:20px;padding:0 0 20px}.sessionbar p{margin:0}.muted{color:#59665f}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{overflow:auto;background:var(--soft);border:1px solid var(--line);border-radius:18px 18px 5px 18px;padding:20px;margin:12px 0}h2,h3{letter-spacing:-.03em}button{min-height:44px;border-radius:999px;padding:0 15px}button:hover{background:var(--signal)}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--signal);outline-offset:3px}input,select{min-height:44px;max-width:100%;padding:10px;margin:3px;border:1px solid rgba(17,21,18,.3);border-radius:7px;background:#fff}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid rgba(17,21,18,.14)}.danger{color:#84251f}button.danger{border-color:#9c2d25;background:#fff7f4}.actions,.filters,.grant-controls{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.filters{margin:14px 0}.grant-controls{margin-top:10px}.memory-content{max-width:440px}.details{font-size:13px;color:#52615b}code{font:12px ui-monospace,Menlo,monospace}.grid .card b{font-size:1.45rem;color:var(--vault)}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}.button-link:hover,button:hover{transform:none}}
@media(max-width:760px){.topbar{min-height:66px;padding-inline:18px}.wordmark,.wordmark img{width:92px}.topbar__meta span:not(.return-mark){display:none}main,.dashboard-shell{width:min(calc(100% - 28px),1180px)}.onboarding{padding:64px 0}.onboarding__hero{grid-template-columns:1fr;gap:36px}.onboarding h1{font-size:clamp(3.25rem,15vw,5rem)}.cta-row{align-items:stretch;flex-direction:column}.button-link{width:100%}.onboarding__proof{grid-template-columns:1fr;margin-top:64px}.proof{min-height:0}.proof span{margin-bottom:20px}.onboarding__note{align-items:flex-start;flex-direction:column}.sessionbar{align-items:flex-start;flex-direction:column}}
</style></head><body>
<header class="topbar"><a class="wordmark" href="https://ninai.io" aria-label="Ninai website"><img src="https://ninai.io/assets/ninai-wordmark.svg" alt="Ninai"></a><div class="topbar__meta"><span>Hosted AI memory</span><img class="return-mark" src="https://ninai.io/assets/ninai-app-icon.svg" alt=""></div></header>
<main><section class="onboarding" id="oauth-login" hidden><div class="onboarding__hero"><div><p class="eyebrow">Ninai hosted · public beta</p><h1>Remember the project across Claude and ChatGPT.</h1></div><div class="onboarding__intro"><p>Your AI should remember the work. Not your whole life. Create one private workspace, then choose which project Claude or ChatGPT may read.</p><div class="cta-row"><a class="button-link button-link--primary" href="/control/login?screen_hint=signup">Create your workspace ↗</a><a class="button-link button-link--secondary" href="/control/login">Sign in</a></div></div></div><div class="onboarding__proof"><article class="proof"><span>01</span><h2>Create one workspace</h2><p>Name the project you want your AI tools to remember.</p></article><article class="proof"><span>02</span><h2>Connect Claude or ChatGPT</h2><p>OAuth creates a connection with zero memory access.</p></article><article class="proof"><span>03</span><h2>Grant one project</h2><p>You choose read or propose access. Revoke it at any time.</p></article></div><div class="onboarding__note"><span>No local Mac memory is uploaded automatically.</span><span><a href="https://ninai.io/privacy/">Privacy</a> · <a href="https://ninai.io/terms/">Terms</a> · <a href="https://ninai.io/install/">Local install</a></span></div></section></main>
<div class="dashboard-shell"><div class="sessionbar" id="oauth-session" hidden><div><strong>Ninai workspace</strong><p class="muted">Signed in · permissions stay under your control</p></div><a class="button-link" href="/control/logout">Sign out</a></div>
<div class="card" id="token-session"><label>Self-hosted access token <input id="token" type="password" autocomplete="off" placeholder="Bearer token"></label>
<button onclick="connect()">Connect</button> <button onclick="disconnect()">Disconnect</button></div><div id="app">Connect to continue.</div></div>
<script>
const oauthEnabled=__NINAI_OAUTH_ENABLED__,oauthSignedIn=__NINAI_OAUTH_SIGNED_IN__;if(oauthEnabled){document.querySelector(oauthSignedIn?'#oauth-session':'#oauth-login').hidden=false;document.querySelector('#token-session').hidden=true;if(!oauthSignedIn){document.querySelector('.dashboard-shell').hidden=true}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accessToken=oauthEnabled?'':(sessionStorage.getItem('ninai_access_token')||'');document.querySelector('#token').value=accessToken;
function connect(){accessToken=document.querySelector('#token').value.trim();sessionStorage.setItem('ninai_access_token',accessToken);load()}
function disconnect(){accessToken='';sessionStorage.removeItem('ninai_access_token');document.querySelector('#token').value='';document.querySelector('#app').textContent='Disconnected.'}
async function api(path,options){if(!oauthEnabled&&!accessToken)throw Error('Enter an access token');let headers={'content-type':'application/json',...(options?.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;let r=await fetch('/api/control'+path,{...options,headers});if(!r.ok){let e=Error(r.status===401&&oauthEnabled?'Your session has expired. Sign in again.':((await r.json()).error||r.statusText));e.status=r.status;throw e}return r.status===204?null:r.json()}
async function act(path,body){await api(path,{method:'POST',body:JSON.stringify(body||{})});load()}
async function createProject(){let name=prompt('Project name');if(name)await act('/projects',{name})}
async function createConnection(){let provider=prompt('Provider: anthropic or openai','anthropic');if(!provider)return;let client_type=provider==='openai'?'codex':'claude-code';let display_name=prompt('Connection name',client_type);if(!display_name)return;let oauth_client_id=prompt('OAuth client ID (the tpc_… ID returned by dynamic registration). Leave blank only in self-hosted PAT mode.','');let created=await api('/connections',{method:'POST',body:JSON.stringify({provider,client_type,display_name,oauth_client_id})});if(created.personal_access_token)alert('Copy this token now. It will not be shown again:\n\n'+created.personal_access_token);await load()}
async function createWorkspace(){let name=prompt('Workspace name','My workspace');if(name){await api('/workspaces',{method:'POST',body:JSON.stringify({name})});alert('Workspace created. Add a project next.');await load()}}
async function grantProject(id){let scope_id=document.querySelector('#grant-'+id)?.value;if(!scope_id)return;await act('/connections/'+id+'/grants',{scope_kind:'project',scope_id,can_read:true,can_propose:true,can_auto_activate:false})}
async function testConnection(id){let result=await api('/connections/'+id+'/test',{method:'POST',body:'{}'});alert('Connection '+result.metadata_json.connection_test.status);await load()}
async function revokeGrant(id){if(confirm('Revoke this scope grant?'))await act('/grants/'+id+'/revoke')}
async function downloadExport(){let data=await api('/export');let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='ninai-'+data.workspace.slug+'-export.json';link.click();URL.revokeObjectURL(link.href)}
async function deleteWorkspace(slug){let value=prompt('This immediately revokes clients and excludes all memories. Type the workspace slug to confirm:\n\n'+slug);if(value!==slug)return;let result=await api('/delete-workspace',{method:'POST',body:JSON.stringify({confirmation:value})});if(result.deleted){disconnect();alert('Workspace deleted and all client access revoked.')}}
function memoryRows(items){return items.map(x=>`<tr><td class="memory-content">${esc(x.content)}<div class="details">${esc(x.memory_type)} · ${esc(x.status)} · ${esc(x.scope_kind)} <code>${esc(x.scope_id)}</code></div></td><td><code>${esc(x.source_uri||'No source')}</code></td><td>${esc(x.updated_at)}</td></tr>`).join('')}
function filterMemories(){let q=document.querySelector('#memory-query').value.toLowerCase();let status=document.querySelector('#memory-status').value;document.querySelectorAll('#memory-table tbody tr').forEach(row=>{row.hidden=!(row.dataset.search.includes(q)&&(!status||row.dataset.status===status))})}
async function load(){try{let [o,m,c,a,p,all]=await Promise.all([api('/overview'),api('/memories?status=proposed'),api('/connections'),api('/activity'),api('/projects'),api('/memories?limit=200')]);let grantLists=await Promise.all(c.items.map(x=>api('/connections/'+x.id+'/grants')));let grants=grantLists.flatMap(x=>x.items);
document.querySelector('#app').innerHTML=`<div class="grid"><div class="card"><b>${o.counts.active_memories}</b><br>Active memories</div><div class="card"><b>${o.counts.proposals}</b><br>Proposals</div><div class="card"><b>${o.counts.active_connections}</b><br>Connections</div><div class="card"><b>${o.counts.disclosures}</b><br>Disclosures</div></div>
<section class="card"><h2>Projects</h2><p class="muted">A project is the smallest useful sharing boundary.</p><button onclick="createProject()">New project</button>${p.items.map(x=>`<p><b>${esc(x.name)}</b> · <code>${esc(x.id)}</code></p>`).join('')||'<p class="muted">Create one project, then connect an AI client.</p>'}</section>
<section class="card"><h2>Review queue</h2>${m.items.length?`<table><tr><th>Memory</th><th>Source</th><th>Action</th></tr>${m.items.map(x=>`<tr><td>${esc(x.content)}</td><td><code>${esc(x.source_uri)}</code></td><td><button onclick="act('/memories/${x.id}/approve')">Approve</button> <button onclick="act('/memories/${x.id}/reject')">Reject</button></td></tr>`).join('')}</table>`:'<p class="muted">No proposals.</p>'}</section>
<section class="card"><h2>Memories</h2><div class="filters"><label>Search <input id="memory-query" oninput="filterMemories()" placeholder="Content, source, or scope"></label><label>Status <select id="memory-status" onchange="filterMemories()"><option value="">All</option><option>active</option><option>proposed</option><option>conflicted</option><option>superseded</option><option>rejected</option><option>deleted</option></select></label></div>${all.items.length?`<table id="memory-table"><thead><tr><th>Memory and scope</th><th>Source</th><th>Updated</th></tr></thead><tbody>${all.items.map(x=>`<tr data-status="${esc(x.status)}" data-search="${esc((x.content+' '+(x.source_uri||'')+' '+x.scope_kind+' '+x.scope_id).toLowerCase())}">${memoryRows([x]).replace(/^<tr>|<\/tr>$/g,'')}</tr>`).join('')}</tbody></table>`:'<p class="muted">No memories.</p>'}</section>
<section class="card"><h2>Connections</h2><p class="muted">Connect Claude and OpenAI separately. A connection receives nothing until you grant a project.</p><button onclick="createConnection()">New provider connection</button>${c.items.map(x=>`<div><p><b>${esc(x.display_name)}</b> · ${esc(x.provider)} · ${esc(x.status)}</p>${x.status==='active'?`<div class="grant-controls"><label>Project <select id="grant-${esc(x.id)}"><option value="">Choose a project</option>${p.items.map(project=>`<option value="${esc(project.id)}">${esc(project.name)}</option>`).join('')}</select></label><button onclick="grantProject('${x.id}')">Grant read + propose</button><button onclick="testConnection('${x.id}')">Test setup</button><button class="danger" onclick="act('/connections/${x.id}/revoke')">Revoke connection</button></div>`:''}</div>`).join('')||'<p class="muted">No AI clients connected yet.</p>'}</section>
<section class="card"><h2>Permissions</h2>${grants.length?`<table><tr><th>Connection</th><th>Scope</th><th>Access</th><th></th></tr>${grants.map(g=>`<tr><td><code>${esc(g.client_connection_id)}</code></td><td>${esc(g.scope_kind)} · <code>${esc(g.scope_id)}</code></td><td>${g.can_read?'read ':''}${g.can_propose?'propose ':''}${g.can_auto_activate?'auto-activate':''}${g.revoked_at?'revoked':''}</td><td>${g.revoked_at?'':`<button class="danger" onclick="revokeGrant('${g.id}')">Revoke grant</button>`}</td></tr>`).join('')}</table>`:'<p class="muted">No scope grants.</p>'}</section>
<section class="card"><h2>Recent disclosures</h2>${a.items.map(x=>`<p><b>${esc(x.tool_name)}</b> · ${esc(x.decision)} · ${esc(x.created_at)}${x.denial_reason?` · ${esc(x.denial_reason)}`:''}</p>`).join('')||'<p class="muted">No activity.</p>'}</section>
<section class="card"><h2>Data and settings</h2><p>Export the workspace, including memories, sources, permissions, and disclosure history.</p><button onclick="downloadExport()">Download workspace export</button><h3>Delete workspace</h3><p>Deletion immediately revokes connected clients and excludes workspace memories from retrieval. Backup retention and hard deletion remain governed by the deployment policy.</p><button class="danger" onclick="deleteWorkspace('${esc(o.workspace.slug)}')">Delete workspace…</button></section>`}catch(e){let expired=e.status===401&&oauthEnabled;let firstTime=e.status===403&&e.message==='Active workspace membership required';document.querySelector('#app').innerHTML=expired?'<div class="card">Your session expired. Sign in again.</div>':firstTime?`<div class="card"><h2>First-time setup</h2><p>Create a workspace to start using Ninai.</p><button onclick="createWorkspace()">Create workspace</button></div>`:`<div class="card"><h2>We could not load your workspace</h2><p class="danger">${esc(e.message)}</p><button onclick="load()">Try again</button></div>`}}if(!oauthEnabled||oauthSignedIn)load();
</script></body></html>"""


def render_control_center(*, oauth_enabled: bool, signed_in: bool = False) -> str:
    return (CONTROL_CENTER_HTML
            .replace("__NINAI_OAUTH_ENABLED__", json.dumps(oauth_enabled))
            .replace("__NINAI_OAUTH_SIGNED_IN__", json.dumps(signed_in)))
