"""Dependency-free control-center page served by the hosted API."""

import json

CONTROL_CENTER_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ninai Control Center</title><style>
:root{font:15px "Avenir Next",Avenir,system-ui,sans-serif;color:#111512;background:#f4efe5;--vault:#0b302b;--paper:#f4efe5;--signal:#ff6846;--permit:#dcef7b;--moss:#9cb5a8}body{max-width:1050px;margin:0 auto;padding:32px}
h1,h2,h3{font-family:"Iowan Old Style",Georgia,serif}h1{margin:0;font-size:2.4rem}.brandline{border-left:5px solid var(--signal);padding:8px 0 8px 18px;margin-bottom:24px}.promise{font-size:1.15rem;margin:4px 0}.muted{color:#59665f}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}
.card{background:#fbf8f1;border:1px solid rgba(17,21,18,.16);border-radius:18px 18px 5px 18px;padding:18px;margin:12px 0}button{cursor:pointer;border:1px solid #111512;border-radius:7px;padding:8px 12px;background:var(--paper)}button:hover{background:var(--signal)}input,select{padding:8px;margin:3px;border:1px solid rgba(17,21,18,.3);border-radius:6px;background:#fff}
table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid rgba(17,21,18,.14)}
.danger{color:#9c2d25}.actions{display:flex;gap:6px;flex-wrap:wrap}.memory-content{max-width:440px}.details{font-size:13px;color:#52615b}code{font:12px ui-monospace,Menlo,monospace}.grid .card b{font-size:1.45rem;color:var(--vault)}</style></head><body>
<header class="brandline"><h1>ninai</h1><p class="promise">Your AI should remember the work. Not your whole life.</p><p class="muted">Hosted invitation beta · approved memory for OpenAI and Claude</p></header>
<div class="card" id="oauth-login" hidden><h2>Start your workspace</h2><p>Create an account or sign in. You choose what each AI may read.</p><a href="/control/login?screen_hint=signup"><button>Create account</button></a> <a href="/control/login"><button>Sign in</button></a></div>
<div class="card" id="oauth-session" hidden><p>Signed in to the hosted beta.</p><a href="/control/logout"><button>Sign out</button></a></div>
<div class="card" id="token-session"><label>Self-hosted access token <input id="token" type="password" autocomplete="off" placeholder="Bearer token"></label>
<button onclick="connect()">Connect</button> <button onclick="disconnect()">Disconnect</button></div><div id="app">Connect to continue.</div>
<script>
const oauthEnabled=__NINAI_OAUTH_ENABLED__,oauthSignedIn=__NINAI_OAUTH_SIGNED_IN__;if(oauthEnabled){document.querySelector(oauthSignedIn?'#oauth-session':'#oauth-login').hidden=false;document.querySelector('#token-session').hidden=true}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accessToken=oauthEnabled?'':(sessionStorage.getItem('ninai_access_token')||'');document.querySelector('#token').value=accessToken;
function connect(){accessToken=document.querySelector('#token').value.trim();sessionStorage.setItem('ninai_access_token',accessToken);load()}
function disconnect(){accessToken='';sessionStorage.removeItem('ninai_access_token');document.querySelector('#token').value='';document.querySelector('#app').textContent='Disconnected.'}
async function api(path,options){if(!oauthEnabled&&!accessToken)throw Error('Enter an access token');let headers={'content-type':'application/json',...(options?.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;let r=await fetch('/api/control'+path,{...options,headers});if(!r.ok){let e=Error(r.status===401&&oauthEnabled?'Your session has expired. Sign in again.':((await r.json()).error||r.statusText));e.status=r.status;throw e}return r.status===204?null:r.json()}
async function act(path,body){await api(path,{method:'POST',body:JSON.stringify(body||{})});load()}
async function createProject(){let name=prompt('Project name');if(name)await act('/projects',{name})}
async function createConnection(){let provider=prompt('Provider: anthropic or openai','anthropic');if(!provider)return;let client_type=provider==='openai'?'codex':'claude-code';let display_name=prompt('Connection name',client_type);if(!display_name)return;let oauth_client_id=prompt('OAuth client ID (the tpc_… ID returned by dynamic registration). Leave blank only in self-hosted PAT mode.','');let created=await api('/connections',{method:'POST',body:JSON.stringify({provider,client_type,display_name,oauth_client_id})});if(created.personal_access_token)alert('Copy this token now. It will not be shown again:\n\n'+created.personal_access_token);await load()}
async function createWorkspace(){let name=prompt('Workspace name','My workspace');if(name){await api('/workspaces',{method:'POST',body:JSON.stringify({name})});alert('Workspace created. Add a project next.');await load()}}
async function grantProject(id){let scope_id=prompt('Project ID to grant');if(!scope_id)return;await act('/connections/'+id+'/grants',{scope_kind:'project',scope_id,can_read:true,can_propose:true,can_auto_activate:false})}
async function testConnection(id){let result=await api('/connections/'+id+'/test',{method:'POST',body:'{}'});alert('Connection '+result.metadata_json.connection_test.status);await load()}
async function revokeGrant(id){if(confirm('Revoke this scope grant?'))await act('/grants/'+id+'/revoke')}
async function downloadExport(){let data=await api('/export');let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='ninai-'+data.workspace.slug+'-export.json';link.click();URL.revokeObjectURL(link.href)}
async function deleteWorkspace(slug){let value=prompt('This immediately revokes clients and excludes all memories. Type the workspace slug to confirm:\n\n'+slug);if(value!==slug)return;let result=await api('/delete-workspace',{method:'POST',body:JSON.stringify({confirmation:value})});if(result.deleted){disconnect();alert('Workspace deleted and all client access revoked.')}}
function memoryRows(items){return items.map(x=>`<tr><td class="memory-content">${esc(x.content)}<div class="details">${esc(x.memory_type)} · ${esc(x.status)} · ${esc(x.scope_kind)} <code>${esc(x.scope_id)}</code></div></td><td><code>${esc(x.source_uri||'No source')}</code></td><td>${esc(x.updated_at)}</td></tr>`).join('')}
function filterMemories(){let q=document.querySelector('#memory-query').value.toLowerCase();let status=document.querySelector('#memory-status').value;document.querySelectorAll('#memory-table tbody tr').forEach(row=>{row.hidden=!(row.dataset.search.includes(q)&&(!status||row.dataset.status===status))})}
async function load(){try{let [o,m,c,a,p,all]=await Promise.all([api('/overview'),api('/memories?status=proposed'),api('/connections'),api('/activity'),api('/projects'),api('/memories?limit=200')]);let grantLists=await Promise.all(c.items.map(x=>api('/connections/'+x.id+'/grants')));let grants=grantLists.flatMap(x=>x.items);
document.querySelector('#app').innerHTML=`<div class="grid"><div class="card"><b>${o.counts.active_memories}</b><br>Active memories</div><div class="card"><b>${o.counts.proposals}</b><br>Proposals</div><div class="card"><b>${o.counts.active_connections}</b><br>Connections</div><div class="card"><b>${o.counts.disclosures}</b><br>Disclosures</div></div>
<section class="card"><h2>Projects</h2><p class="muted">A project is the smallest useful sharing boundary.</p><button onclick="createProject()">New project</button>${p.items.map(x=>`<p><b>${esc(x.name)}</b> · <code>${esc(x.id)}</code></p>`).join('')||'<p class="muted">Create one project, then connect an AI client.</p>'}</section>
<section class="card"><h2>Review queue</h2>${m.items.length?`<table><tr><th>Memory</th><th>Source</th><th>Action</th></tr>${m.items.map(x=>`<tr><td>${esc(x.content)}</td><td><code>${esc(x.source_uri)}</code></td><td><button onclick="act('/memories/${x.id}/approve')">Approve</button> <button onclick="act('/memories/${x.id}/reject')">Reject</button></td></tr>`).join('')}</table>`:'<p class="muted">No proposals.</p>'}</section>
<section class="card"><h2>Memories</h2><label>Search <input id="memory-query" oninput="filterMemories()" placeholder="Content, source, or scope"></label><label>Status <select id="memory-status" onchange="filterMemories()"><option value="">All</option><option>active</option><option>proposed</option><option>conflicted</option><option>superseded</option><option>rejected</option><option>deleted</option></select></label>${all.items.length?`<table id="memory-table"><thead><tr><th>Memory and scope</th><th>Source</th><th>Updated</th></tr></thead><tbody>${all.items.map(x=>`<tr data-status="${esc(x.status)}" data-search="${esc((x.content+' '+(x.source_uri||'')+' '+x.scope_kind+' '+x.scope_id).toLowerCase())}">${memoryRows([x]).replace(/^<tr>|<\/tr>$/g,'')}</tr>`).join('')}</tbody></table>`:'<p class="muted">No memories.</p>'}</section>
<section class="card"><h2>Connections</h2><p class="muted">Connect Claude and OpenAI separately. A connection receives nothing until you grant a project.</p><button onclick="createConnection()">New provider connection</button>${c.items.map(x=>`<p><b>${esc(x.display_name)}</b> · ${esc(x.provider)} · ${esc(x.status)} ${x.status==='active'?`<span class="actions"><button onclick="grantProject('${x.id}')">Grant project</button><button onclick="testConnection('${x.id}')">Test setup</button><button class="danger" onclick="act('/connections/${x.id}/revoke')">Revoke connection</button></span>`:''}</p>`).join('')||'<p class="muted">No AI clients connected yet.</p>'}</section>
<section class="card"><h2>Permissions</h2>${grants.length?`<table><tr><th>Connection</th><th>Scope</th><th>Access</th><th></th></tr>${grants.map(g=>`<tr><td><code>${esc(g.client_connection_id)}</code></td><td>${esc(g.scope_kind)} · <code>${esc(g.scope_id)}</code></td><td>${g.can_read?'read ':''}${g.can_propose?'propose ':''}${g.can_auto_activate?'auto-activate':''}${g.revoked_at?'revoked':''}</td><td>${g.revoked_at?'':`<button class="danger" onclick="revokeGrant('${g.id}')">Revoke grant</button>`}</td></tr>`).join('')}</table>`:'<p class="muted">No scope grants.</p>'}</section>
<section class="card"><h2>Recent disclosures</h2>${a.items.map(x=>`<p><b>${esc(x.tool_name)}</b> · ${esc(x.decision)} · ${esc(x.created_at)}${x.denial_reason?` · ${esc(x.denial_reason)}`:''}</p>`).join('')||'<p class="muted">No activity.</p>'}</section>
<section class="card"><h2>Data and settings</h2><p>Export the workspace, including memories, sources, permissions, and disclosure history.</p><button onclick="downloadExport()">Download workspace export</button><h3 class="danger">Delete workspace</h3><p>Deletion immediately revokes connected clients and excludes workspace memories from retrieval. Backup retention and hard deletion remain governed by the deployment policy.</p><button class="danger" onclick="deleteWorkspace('${esc(o.workspace.slug)}')">Delete workspace…</button></section>`}catch(e){document.querySelector('#app').innerHTML=e.status===401&&oauthEnabled?'<div class="card">Choose Create account or Sign in above to continue.</div>':`<div class="card danger">${esc(e.message)}</div><div class="card"><h2>First-time setup</h2><p>Create a workspace when your authenticated account has not joined one yet.</p><button onclick="createWorkspace()">Create workspace</button></div>`}}load();
</script></body></html>"""


def render_control_center(*, oauth_enabled: bool, signed_in: bool = False) -> str:
    return (CONTROL_CENTER_HTML
            .replace("__NINAI_OAUTH_ENABLED__", json.dumps(oauth_enabled))
            .replace("__NINAI_OAUTH_SIGNED_IN__", json.dumps(signed_in)))
