"""Dependency-free control-center page served by the hosted API."""

import json

CONTROL_CENTER_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b302b"><link rel="icon" type="image/svg+xml" href="/favicon.svg?v=2"><link rel="shortcut icon" href="/favicon.svg?v=2"><link rel="apple-touch-icon" href="/favicon.svg?v=2">
<title>Ninai Control Center — Hosted AI memory</title><style>
:root{font:15px "Avenir Next",Avenir,system-ui,sans-serif;color:#111512;background:#f4efe5;--vault:#0b302b;--paper:#f4efe5;--soft:#fbf8f1;--signal:#ff6846;--permit:#dcef7b;--moss:#9cb5a8;--line:rgba(17,21,18,.18)}*{box-sizing:border-box}html{background:var(--paper)}body{margin:0;background:var(--paper)}
.topbar{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);padding:0 max(24px,calc((100vw - 1180px)/2));background:rgba(244,239,229,.94)}.wordmark{width:112px;display:inline-flex;align-items:center;text-decoration:none}.wordmark img{width:112px;height:auto;display:block}.topbar__meta{display:flex;align-items:center;gap:12px;color:#52615b;font:11px ui-monospace,Menlo,monospace;letter-spacing:.08em;text-transform:uppercase}.return-mark{width:24px;height:24px;display:block;border-radius:7px}
main,.dashboard-shell{width:min(calc(100% - 48px),1180px);margin:0 auto}.onboarding{padding:clamp(70px,9vw,130px) 0 80px}.onboarding__hero{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:clamp(50px,9vw,130px);align-items:end}.eyebrow{margin:0 0 22px;color:#52615b;font:11px ui-monospace,Menlo,monospace;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.onboarding h1{max-width:780px;margin:0;font-size:clamp(4rem,7.2vw,7.2rem);font-weight:850;letter-spacing:-.075em;line-height:.86}.onboarding__intro{padding-bottom:8px}.onboarding__intro p{margin:0 0 28px;color:#52615b;font-size:1.15rem;line-height:1.55}.cta-row{display:flex;flex-wrap:wrap;gap:12px}.button-link,button{min-height:48px;display:inline-flex;align-items:center;justify-content:center;border:1px solid #111512;border-radius:999px;padding:0 22px;cursor:pointer;color:#111512;background:var(--paper);font:inherit;font-weight:800;text-decoration:none}.button-link--primary{background:var(--signal);box-shadow:7px 7px 0 var(--vault)}.button-link--secondary{color:var(--paper);background:var(--vault)}button:hover,.button-link:hover{transform:translateY(-2px)}
.onboarding__proof{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;border-top:1px solid var(--line);margin-top:90px;padding-top:28px}.proof{min-height:150px;border:1px solid var(--line);border-radius:24px 24px 7px 24px;padding:24px;background:var(--soft)}.proof span{display:inline-grid;width:30px;height:30px;place-items:center;border:1px solid var(--vault);border-radius:50%;margin-bottom:30px;color:var(--vault);background:var(--permit);font:11px ui-monospace,Menlo,monospace}.proof h2{margin:0 0 8px;font-size:1.15rem}.proof p{margin:0;color:#59665f;line-height:1.5}.onboarding__note{display:flex;justify-content:space-between;gap:30px;border-top:1px solid var(--line);margin-top:28px;padding-top:18px;color:#59665f;font-size:.82rem}.onboarding__note a{color:inherit}
.dashboard-shell{padding:34px 0 80px}.sessionbar{display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);margin-bottom:20px;padding:0 0 20px}.sessionbar p{margin:0}.muted{color:#59665f}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{overflow:auto;background:var(--soft);border:1px solid var(--line);border-radius:18px 18px 5px 18px;padding:20px;margin:12px 0}.card>h2:first-child{margin-top:0}h2,h3{letter-spacing:-.03em}button{min-height:44px;border-radius:999px;padding:0 15px}button:hover{background:var(--signal)}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid var(--signal);outline-offset:3px}input,select{width:100%;min-height:44px;max-width:100%;padding:10px;border:1px solid rgba(17,21,18,.3);border-radius:7px;background:#fff}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid rgba(17,21,18,.14)}.danger{color:#84251f}button.danger{border-color:#9c2d25;background:#fff7f4}.actions,.filters,.grant-controls{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.filters{margin:14px 0}.grant-controls{margin-top:10px}.memory-content{max-width:440px}.details{font-size:13px;color:#52615b}code{font:12px ui-monospace,Menlo,monospace}.grid .card b{font-size:1.45rem;color:var(--vault)}
.form-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;align-items:end;margin:16px 0}.field{display:grid;gap:6px;font-weight:750}.field small{color:#59665f;font-weight:500;line-height:1.4}.notice{border:1px solid var(--vault);border-left:6px solid var(--permit);border-radius:12px;padding:14px 16px;margin:0 0 16px;background:var(--soft)}.notice:empty{display:none}.notice--error{border-left-color:var(--signal)}.notice__actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.setup-card{border-color:var(--vault);background:#eef2dc}.setup-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.setup-step{border:1px solid var(--line);border-radius:14px;padding:14px;background:var(--soft)}.setup-step--done{background:#f2f7d7}.setup-step span{display:block;color:#59665f;font:11px ui-monospace,Menlo,monospace;text-transform:uppercase}.provider-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:16px 0}.provider-card{border:1px solid var(--line);border-radius:14px;padding:16px;background:#fff}.provider-card h3{margin:0 0 6px}.status{display:inline-flex;border:1px solid currentColor;border-radius:999px;padding:4px 8px;color:#52615b;font:10px ui-monospace,Menlo,monospace;text-transform:uppercase}.connection{border-top:1px solid var(--line);padding:16px 0}.connection:first-of-type{margin-top:18px}.advanced{border-top:1px solid var(--line);margin-top:18px;padding-top:14px}.advanced summary{cursor:pointer;font-weight:800}.danger-zone{border-color:rgba(156,45,37,.5);background:#fff7f4}summary{cursor:pointer}.settings-card>summary{font-size:1.2rem;font-weight:850}.secret{overflow-wrap:anywhere;font-family:ui-monospace,Menlo,monospace}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}.button-link:hover,button:hover{transform:none}}
@media(max-width:760px){.topbar{min-height:66px;padding-inline:18px}.wordmark,.wordmark img{width:92px}.topbar__meta span:not(.return-mark){display:none}main,.dashboard-shell{width:min(calc(100% - 28px),1180px)}.onboarding{padding:64px 0}.onboarding__hero{grid-template-columns:1fr;gap:36px}.onboarding h1{font-size:clamp(3.25rem,15vw,5rem)}.cta-row{align-items:stretch;flex-direction:column}.button-link{width:100%}.onboarding__proof,.setup-steps,.provider-grid{grid-template-columns:1fr}.onboarding__proof{margin-top:64px}.proof{min-height:0}.proof span{margin-bottom:20px}.onboarding__note{align-items:flex-start;flex-direction:column}.sessionbar{align-items:flex-start;flex-direction:column}.form-row{grid-template-columns:1fr}.form-row button{width:100%}}
</style></head><body>
<header class="topbar"><a class="wordmark" href="https://ninai.io" aria-label="Ninai website"><img src="https://ninai.io/assets/ninai-wordmark.svg" alt="Ninai"></a><div class="topbar__meta"><span>Hosted AI memory</span><img class="return-mark" src="https://ninai.io/assets/ninai-app-icon.svg" alt=""></div></header>
<main><section class="onboarding" id="oauth-login" hidden><div class="onboarding__hero"><div><p class="eyebrow">Ninai hosted · public beta</p><h1>Remember the project across Claude and ChatGPT.</h1></div><div class="onboarding__intro"><p>Your AI should remember the work. Not your whole life. Create one private workspace, then choose which project Claude or ChatGPT may read.</p><div class="cta-row"><a class="button-link button-link--primary" href="/control/login?screen_hint=signup">Create your workspace ↗</a><a class="button-link button-link--secondary" href="/control/login">Sign in</a></div></div></div><div class="onboarding__proof"><article class="proof"><span>01</span><h2>Create one workspace</h2><p>Name the project you want your AI tools to remember.</p></article><article class="proof"><span>02</span><h2>Connect Claude or ChatGPT</h2><p>OAuth creates a connection with zero memory access.</p></article><article class="proof"><span>03</span><h2>Grant one project</h2><p>You choose read or propose access. Revoke it at any time.</p></article></div><div class="onboarding__note"><span>No local Mac memory is uploaded automatically.</span><span><a href="https://ninai.io/privacy/">Privacy</a> · <a href="https://ninai.io/terms/">Terms</a> · <a href="https://ninai.io/install/">Local install</a></span></div></section></main>
<div class="dashboard-shell"><div class="sessionbar" id="oauth-session" hidden><div><strong>Ninai workspace</strong><p class="muted">Signed in · permissions stay under your control</p></div><a class="button-link" href="/control/logout">Sign out</a></div>
<div class="card" id="token-session"><label>Self-hosted access token <input id="token" type="password" autocomplete="off" placeholder="Bearer token"></label>
<button onclick="connect()">Connect</button> <button onclick="disconnect()">Disconnect</button></div><div id="notice" class="notice" role="status" aria-live="polite"></div><div id="app">Connect to continue.</div></div>
<script>
const oauthEnabled=__NINAI_OAUTH_ENABLED__,oauthSignedIn=__NINAI_OAUTH_SIGNED_IN__;if(oauthEnabled){document.querySelector(oauthSignedIn?'#oauth-session':'#oauth-login').hidden=false;document.querySelector('#token-session').hidden=true;if(!oauthSignedIn){document.querySelector('.dashboard-shell').hidden=true}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accessToken=oauthEnabled?'':(sessionStorage.getItem('ninai_access_token')||'');document.querySelector('#token').value=accessToken;
function connect(){accessToken=document.querySelector('#token').value.trim();sessionStorage.setItem('ninai_access_token',accessToken);load()}
function disconnect(){accessToken='';sessionStorage.removeItem('ninai_access_token');document.querySelector('#token').value='';document.querySelector('#app').textContent='Disconnected.'}
let pendingConfirmation=null,currentSecret='';
function notify(message,tone=''){let box=document.querySelector('#notice');box.className='notice'+(tone?' notice--'+tone:'');box.textContent=message;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
function showSecret(token){currentSecret=token;let box=document.querySelector('#notice');box.className='notice';box.innerHTML=`<b>Copy this access token now.</b><p class="secret">${esc(token)}</p><div class="notice__actions"><button onclick="copySecret()">Copy token</button><button onclick="clearNotice()">Done</button></div>`}
async function copySecret(){try{await navigator.clipboard.writeText(currentSecret);notify('Access token copied. Store it securely; Ninai will not show it again.')}catch(_){notify('Copy failed. Select the token and copy it manually.','error')}}
async function copyEndpoint(){try{await navigator.clipboard.writeText(location.origin+'/mcp');notify('Ninai MCP address copied. Add it in Claude or ChatGPT, then return here to choose project access.')}catch(_){notify('Copy failed. Use '+location.origin+'/mcp','error')}}
function clearNotice(){let box=document.querySelector('#notice');box.className='notice';box.textContent='';pendingConfirmation=null;currentSecret=''}
function askConfirmation(message,action,label='Confirm'){pendingConfirmation=action;let box=document.querySelector('#notice');box.className='notice notice--error';box.innerHTML=`<b>${esc(message)}</b><div class="notice__actions"><button class="danger" onclick="confirmPending()">${esc(label)}</button><button onclick="clearNotice()">Cancel</button></div>`;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function confirmPending(){let action=pendingConfirmation;pendingConfirmation=null;if(action)await action()}
async function api(path,options){if(!oauthEnabled&&!accessToken)throw Error('Enter an access token');let headers={'content-type':'application/json',...(options?.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;let r=await fetch('/api/control'+path,{...options,headers});if(!r.ok){let e=Error(r.status===401&&oauthEnabled?'Your session has expired. Sign in again.':((await r.json()).error||r.statusText));e.status=r.status;throw e}return r.status===204?null:r.json()}
async function act(path,body,success){try{await api(path,{method:'POST',body:JSON.stringify(body||{})});await load();if(success)notify(success)}catch(e){notify(e.message,'error')}}
async function createProject(event){event.preventDefault();let name=document.querySelector('#project-name').value.trim();if(!name){notify('Enter a project name.','error');return}await act('/projects',{name},'Project created. Next, connect Claude or ChatGPT.')}
async function createConnection(event){event.preventDefault();let form=event.currentTarget,provider=form.provider.value,client_type=provider==='openai'?'codex':'claude-code',display_name=form.display_name.value.trim(),oauth_client_id=form.oauth_client_id.value.trim();if(!display_name){notify('Enter a connection name.','error');return}try{let created=await api('/connections',{method:'POST',body:JSON.stringify({provider,client_type,display_name,oauth_client_id})});await load();if(created.personal_access_token)showSecret(created.personal_access_token);else notify('Connection added. Choose a project and grant access.') }catch(e){notify(e.message,'error')}}
async function createWorkspace(event){event.preventDefault();let name=document.querySelector('#workspace-name').value.trim();if(!name){notify('Enter a workspace name.','error');return}try{await api('/workspaces',{method:'POST',body:JSON.stringify({name})});await load();notify('Workspace created. Add your first project.')}catch(e){notify(e.message,'error')}}
async function grantProject(id){let scope_id=document.querySelector('#grant-'+id)?.value;if(!scope_id){notify('Choose a project first.','error');return}await act('/connections/'+id+'/grants',{scope_kind:'project',scope_id,can_read:true,can_propose:true,can_auto_activate:false},'Project access granted. Test the connection when you are ready.')}
async function testConnection(id){try{let result=await api('/connections/'+id+'/test',{method:'POST',body:'{}'});notify('Connection '+result.metadata_json.connection_test.status+'. Ninai is ready to use.')}catch(e){notify(e.message,'error')}}
function revokeGrant(id){askConfirmation('Revoke this project grant? The AI will immediately lose this access.',()=>act('/grants/'+id+'/revoke',{},'Project access revoked.'),'Revoke access')}
function revokeConnection(id){askConfirmation('Disconnect this AI? Its project grants will be revoked immediately.',()=>act('/connections/'+id+'/revoke',{},'AI connection revoked.'),'Disconnect AI')}
async function downloadExport(){let data=await api('/export');let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='ninai-'+data.workspace.slug+'-export.json';link.click();URL.revokeObjectURL(link.href)}
function deleteWorkspace(slug){let value=document.querySelector('#delete-confirmation').value.trim();if(value!==slug){notify('Type the workspace slug exactly to confirm deletion.','error');return}askConfirmation('Permanently delete this workspace and revoke every connected AI?',async()=>{try{let result=await api('/delete-workspace',{method:'POST',body:JSON.stringify({confirmation:value})});if(result.deleted){disconnect();notify('Workspace deleted and all AI access revoked.')}}catch(e){notify(e.message,'error')}},'Delete workspace')}
function memoryRows(items){return items.map(x=>`<tr><td class="memory-content">${esc(x.content)}<div class="details">${esc(x.memory_type)} · ${esc(x.status)} · ${esc(x.scope_kind)} <code>${esc(x.scope_id)}</code></div></td><td><code>${esc(x.source_uri||'No source')}</code></td><td>${esc(x.updated_at)}</td></tr>`).join('')}
function filterMemories(){let q=document.querySelector('#memory-query').value.toLowerCase();let status=document.querySelector('#memory-status').value;document.querySelectorAll('#memory-table tbody tr').forEach(row=>{row.hidden=!(row.dataset.search.includes(q)&&(!status||row.dataset.status===status))})}
async function load(){try{let [o,m,c,a,p,all]=await Promise.all([api('/overview'),api('/memories?status=proposed'),api('/connections'),api('/activity'),api('/projects'),api('/memories?limit=200')]);let grantLists=await Promise.all(c.items.map(x=>api('/connections/'+x.id+'/grants')));let grants=grantLists.flatMap(x=>x.items);
let activeConnections=c.items.filter(x=>x.status==='active'),activeGrants=grants.filter(x=>!x.revoked_at),projectName=id=>p.items.find(x=>x.id===id)?.name||'Project',connectionName=id=>c.items.find(x=>x.id===id)?.display_name||'AI connection';
document.querySelector('#app').innerHTML=`<section class="card setup-card"><h2>Finish setup</h2><p class="muted">One project, one AI connection, one explicit grant.</p><div class="setup-steps"><div class="setup-step ${p.items.length?'setup-step--done':''}"><span>1 · ${p.items.length?'Complete':'Next'}</span><b>Name a project</b></div><div class="setup-step ${activeConnections.length?'setup-step--done':''}"><span>2 · ${activeConnections.length?'Complete':p.items.length?'Next':'Waiting'}</span><b>Connect an AI</b></div><div class="setup-step ${activeGrants.length?'setup-step--done':''}"><span>3 · ${activeGrants.length?'Complete':activeConnections.length?'Next':'Waiting'}</span><b>Choose access</b></div></div></section>
<div class="grid"><div class="card"><b>${o.counts.active_memories}</b><br>Approved memories</div><div class="card"><b>${o.counts.proposals}</b><br>Awaiting review</div><div class="card"><b>${o.counts.active_connections}</b><br>Connected AI tools</div></div>
<section class="card"><h2>Projects</h2><p class="muted">A project is the smallest useful sharing boundary.</p><form class="form-row" onsubmit="createProject(event)"><label class="field">Project name<input id="project-name" name="project_name" required maxlength="120" placeholder="e.g. Ninai launch"></label><button type="submit">Add project</button></form>${p.items.map(x=>`<p><b>${esc(x.name)}</b>${x.description?` · ${esc(x.description)}`:''}</p>`).join('')||'<p class="muted">Add the first project you want an AI to remember.</p>'}</section>
<section class="card"><h2>Review queue</h2>${m.items.length?`<table><tr><th>Memory</th><th>Source</th><th>Action</th></tr>${m.items.map(x=>`<tr><td>${esc(x.content)}</td><td><code>${esc(x.source_uri)}</code></td><td><button onclick="act('/memories/${x.id}/approve')">Approve</button> <button onclick="act('/memories/${x.id}/reject')">Reject</button></td></tr>`).join('')}</table>`:'<p class="muted">No proposals.</p>'}</section>
<section class="card"><h2>AI connections</h2><p class="muted">Add Ninai in your AI tool. OAuth connections appear here with zero memory access until you choose a project.</p><div class="provider-grid"><article class="provider-card"><span class="status">${c.items.some(x=>x.provider==='anthropic'&&x.status==='active')?'Connected':'Not connected'}</span><h3>Claude</h3><p class="muted">Connect the hosted Ninai MCP service, then return here to grant a project.</p><div class="actions"><button onclick="copyEndpoint()">Copy MCP address</button><a href="https://ninai.io/install/#hosted-claude">Setup guide →</a></div></article><article class="provider-card"><span class="status">${c.items.some(x=>x.provider==='openai'&&x.status==='active')?'Connected':'Not connected'}</span><h3>ChatGPT</h3><p class="muted">Add Ninai as an app during beta, then return here to grant a project.</p><div class="actions"><button onclick="copyEndpoint()">Copy MCP address</button><a href="https://ninai.io/install/#hosted-openai">Setup guide →</a></div></article></div>${c.items.map(x=>`<div class="connection"><p><b>${esc(x.display_name)}</b> · ${esc(x.provider)} <span class="status">${esc(x.status)}</span></p>${x.status==='active'?`<div class="grant-controls"><label class="field">Project<select id="grant-${esc(x.id)}"><option value="">Choose a project</option>${p.items.map(project=>`<option value="${esc(project.id)}">${esc(project.name)}</option>`).join('')}</select></label><button onclick="grantProject('${x.id}')">Grant read + propose</button><button onclick="testConnection('${x.id}')">Test connection</button><button class="danger" onclick="revokeConnection('${x.id}')">Disconnect</button></div>`:''}</div>`).join('')||'<p class="muted">No AI connected yet.</p>'}<details class="advanced"><summary>Manual beta connection</summary><p class="muted">Only use this if the connector gave you an OAuth client ID.</p><form class="form-row" onsubmit="createConnection(event)"><label class="field">Provider<select name="provider"><option value="anthropic">Claude</option><option value="openai">ChatGPT</option></select></label><label class="field">Connection name<input name="display_name" required placeholder="e.g. Claude work"></label><label class="field">OAuth client ID<input name="oauth_client_id" placeholder="tpc_…"><small>Created during connector authorization.</small></label><button type="submit">Add connection</button></form></details></section>
<details class="card settings-card"><summary>Permissions</summary>${grants.length?`<table><tr><th>AI</th><th>Project</th><th>Access</th><th></th></tr>${grants.map(g=>`<tr><td>${esc(connectionName(g.client_connection_id))}</td><td>${esc(projectName(g.scope_id))}</td><td>${g.can_read?'Read ':''}${g.can_propose?'Propose ':''}${g.can_auto_activate?'Auto-approve':''}${g.revoked_at?'Revoked':''}</td><td>${g.revoked_at?'':`<button class="danger" onclick="revokeGrant('${g.id}')">Revoke</button>`}</td></tr>`).join('')}</table>`:'<p class="muted">No project access granted.</p>'}</details>
<details class="card settings-card"><summary>Memories</summary><div class="filters"><label class="field">Search<input id="memory-query" oninput="filterMemories()" placeholder="Content, source, or project"></label><label class="field">Status<select id="memory-status" onchange="filterMemories()"><option value="">All</option><option>active</option><option>proposed</option><option>conflicted</option><option>superseded</option><option>rejected</option><option>deleted</option></select></label></div>${all.items.length?`<table id="memory-table"><thead><tr><th>Memory and scope</th><th>Source</th><th>Updated</th></tr></thead><tbody>${all.items.map(x=>`<tr data-status="${esc(x.status)}" data-search="${esc((x.content+' '+(x.source_uri||'')+' '+x.scope_kind+' '+x.scope_id).toLowerCase())}">${memoryRows([x]).replace(/^<tr>|<\/tr>$/g,'')}</tr>`).join('')}</tbody></table>`:'<p class="muted">No memories yet.</p>'}</details>
<section class="card"><h2>Recent disclosures</h2>${a.items.map(x=>`<p><b>${esc(x.tool_name)}</b> · ${esc(x.decision)} · ${esc(x.created_at)}${x.denial_reason?` · ${esc(x.denial_reason)}`:''}</p>`).join('')||'<p class="muted">No activity.</p>'}</section>
<details class="card settings-card"><summary>Data and settings</summary><p>Export memories, sources, permissions, and disclosure history.</p><button onclick="downloadExport()">Download workspace export</button><div class="card danger-zone"><h3>Delete workspace</h3><p>Type <b>${esc(o.workspace.slug)}</b> to permanently revoke every connected AI and delete this workspace.</p><div class="form-row"><label class="field">Workspace slug<input id="delete-confirmation" autocomplete="off"></label><button class="danger" onclick="deleteWorkspace('${esc(o.workspace.slug)}')">Delete workspace</button></div></div></details>`}catch(e){let expired=e.status===401&&oauthEnabled;let firstTime=e.status===403&&e.message==='Active workspace membership required';document.querySelector('#app').innerHTML=expired?'<div class="card">Your session expired. Sign in again.</div>':firstTime?`<div class="card setup-card"><h2>Create your workspace</h2><p>Start with one workspace for your AI memory.</p><form class="form-row" onsubmit="createWorkspace(event)"><label class="field">Workspace name<input id="workspace-name" required maxlength="120" value="My workspace"></label><button type="submit">Create workspace</button></form></div>`:`<div class="card"><h2>We could not load your workspace</h2><p class="danger">${esc(e.message)}</p><button onclick="load()">Try again</button></div>`}}if(!oauthEnabled||oauthSignedIn)load();
</script></body></html>"""


def render_control_center(*, oauth_enabled: bool, signed_in: bool = False) -> str:
    return (CONTROL_CENTER_HTML
            .replace("__NINAI_OAUTH_ENABLED__", json.dumps(oauth_enabled))
            .replace("__NINAI_OAUTH_SIGNED_IN__", json.dumps(signed_in)))
